In [1]:
import numpy as np
import torch
import torch.nn as nn

In [11]:
f=nn.Linear(4,2)
print(f.weight.data)
nn.init.orthogonal(f.weight.data)
f.weight.data@f.weight.data.T

tensor([[ 0.3507,  0.3688, -0.1052, -0.4695],
        [-0.3754,  0.3737,  0.1169,  0.4543]])


C:\Users\hmppc\AppData\Local\Temp/ipykernel_17336/2793755268.py:3: UserWarning: nn.init.orthogonal is now deprecated in favor of nn.init.orthogonal_.
  nn.init.orthogonal(f.weight.data)


tensor([[ 1.0000e+00, -4.4703e-08],
        [-4.4703e-08,  1.0000e+00]])

In [15]:
x=np.asarray([[[1,2,3],
               [4,5,6]],
              [[2,4,6],
               [1,3,5]]])
np.concatenate(x)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6],
       [1, 3, 5]])

In [14]:
print(x)
print(y)

tensor([[0., 1., 1., 1., 1.]])
tensor([[-0.4166, -0.0751,  1.1851, -0.4429, -0.2869,  0.2777, -0.0319, -0.8016,
         -1.2290, -0.1750]], grad_fn=<AddmmBackward0>)


In [31]:
z=torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
z.sum(2,keepdim=True)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [48]:
x=torch.tensor([2.],requires_grad=True)
y=x*x
y.backward()
print(x.grad)


tensor([4.])


In [41]:
x.grad=None